cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'puma/puma'

brew 'ack'
brew 'coreutils'
brew 'git'
brew 'grc'
brew 'imagemagick'
brew 'jq'
brew 'libgit2'
brew 'openssl'
brew 'mackup'
brew 'mas'
brew 'readline'
brew 'postgresql'
brew 'unrar'
brew 'wget'
brew 'watch'
brew 'zsh'
brew 'zsh-completions'
brew 'zplug'

# cask '1password' # using mac store version
cask 'adium'
cask 'alfred'
cask 'appcleaner'
cask 'beamer'
cask 'browser-chooserx'
cask 'caffeine'
cask 'dash'
cask 'dropbox'
cask 'iterm2'
cask 'evernote'
cask 'firefox'
cask 'flux'
cask 'fluid'
cask 'kap'
cask 'google-chrome'
cask 'handbrake'
cask 'moom'
cask 'paw'
cask 'postico'
cask 'rdm'
cask 'rowanj-gitx'
cask 'sketch'
cask 'slack'
cask 'spotify'
cask 'sourcetree'
cask 'sublime-text'
cask 'the-unarchiver'
cask 'tunnelbear'
cask 'utc-menu-clock'
cask 'vlc'
