cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'puma/puma'

brew 'ack'
brew 'automake'
brew 'coreutils'
brew 'git'
brew 'grc'
brew 'imagemagick'
brew 'jq'
brew 'openssl'
# brew 'TomAnthony/brews/itermocil'
brew 'mackup'
brew 'mas'
brew 'readline'
brew 'postgresql'
brew 'unrar'
brew 'wget'
brew 'watch'
brew 'wifi-password'
brew 'zsh'
brew 'zsh-completions'
brew 'autojump'

cask '1password'
cask 'alfred'
cask 'appcleaner'
cask 'beamer'
cask 'caffeine'
cask 'choosy'
cask 'dash'
cask 'dropbox'
cask 'iterm2'
cask 'firefox'
cask 'fluid'
cask 'google-chrome'
cask 'paw'
cask 'postico'
cask 'sketch'
cask 'slack'
cask 'spotify'
cask 'sourcetree'
cask 'sublime-text'
cask 'the-unarchiver'
cask 'tunnelbear'
cask 'utc-menu-clock'
cask 'visual-studio-code'
