#!/usr/bin/env bash
#
# bootstrap installs things.
export ZSH=$HOME/.dotfiles

echo ''
echo 'Installing dotfiles...'
$ZSH/script/install-dotfiles.sh

echo 'Running through all install.sh...'
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done

echo 'Set macOS defaults...'
$ZSH/macos/set-defaults.sh

echo ''
echo 'All installed!'
