#!/usr/bin/env bash
#
# bootstrap installs things.
export ZSH=$HOME/.dotfiles

echo ''
echo 'Installing dotfiles...'
$ZSH/script/install-dotfiles.sh

echo 'Set macOS defaults...'
$ZSH/macos/set-defaults.sh

echo 'Installing homebrew...'
$ZSH/homebrew/install.sh 2>&1

echo 'Running through all install.sh...'
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done

echo 'Mackup restore...'
mackup restore # restore all senstive config/settings

echo ''
echo 'All installed!'
